Address Til's comments.
scionassociation/scion-cp_I-D pull request #80
Opened 2024-12-20 14:51 UTC by jiceatscion

Fixes #46

2024-12-24 12:37 UTC, nicorusti commented
Thanks a lot, I'll review after holidays!

2025-02-04 15:16 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
> +- *Intra-ISD beaconing* creates path segments from core ASes to non-core ASes. For this, the Control Services of core ASes create PCBs and sends them to the non-core child ASes (typically customer AS
without any customer -> without any children

2025-02-21 18:51 UTC, nicorusti requested changes
@jiceatscion I left a few comments, can you have a look? W can then discuss

@tzaeschke , feel free to also have a look , we are trying to address your remaining points from #46

2025-02-21 18:51 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
>  Recovering from a partitioned network is also seamless as only coarse time synchronization between the partitions is required to resume normal operation and move forward with updates of the cryptogra
I think referencing this section would address Til's comment: 
> Also: Does "Healing" include "adding new links"? In this case we also need to wait for the propagation interval and the origination interval.
As I understand, with propagation interval being set to e.g. 10Minutes, this adds up to 5hops1/210min= 25minutes for 5 hops.

```suggestion
Recovering from a partitioned network is also seamless as only coarse time synchronization between the partitions is required to resume normal operation and move forward with updates of the cryptographic material. [](#clock-inaccuracy) further describes the impact of time synchronization and [](#clock-inaccuracy) the impact of path discovery time.
```

Also, we don't set an upper bound to propagation interval. Shall we?

2025-02-21 18:51 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +The process of using PCBs to construct segments is described in details in [](#path-segment-reg)
```suggestion
On its way, a PCB accumulates cryptographically protected path and forwarding information per traversed AS. At every AS, metadata as well as information about the AS's ingress and egress interfaces is added to the PCB. The full PCB message format is described in [](#pcbs). PCBs are used to construct path segments. ASes register them to make them available to other ASes, as described in [](#path-segment-reg).
```

2025-02-21 18:51 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +For the purpose of validation, a timestamp is considered "future" if it is later than the current time at the point of validation plus an allowance for differences between local and origination clock
```suggestion
For the purpose of validation, a timestamp is considered "future" if it is later than the current time at the point of validation plus an allowance for differences between the validator's and originator's clock. As an allowance, it is recommended to use the granularity of the hopfield expiration time (that is 337.5 seconds, see [](#hopfield)).
```

2025-02-24 11:38 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
> +- Availability of certificates: In SCION, every entity is required to be in possession of all cryptographic material (including the ISD's TRC and certificates) that is needed to verify any message it
Explaining bootstraping flows is always hard...
The statement about knowing only immediate neighbors is absolutely true.
The path to a core AS comes from beaconing; which is enabled by having connectivity with only the immediate parent and children ASes. One-hop paths can be crafted without any prior communication. If beaconing works, then all ASes learn paths to core ASes; which they can then query to obtain segments to construct all other paths.

2025-02-24 11:38 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
>  Recovering from a partitioned network is also seamless as only coarse time synchronization between the partitions is required to resume normal operation and move forward with updates of the cryptogra
Did you refer to the same clock-inaccuracy sectoin twice in a row, in your suggestion?

2025-02-24 11:38 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
> +## Bootstrapping ability
Do you mean to replace the title "Bootstrapping" with "PKI-network circular dependency"? Why? Certificates aren't the only objects involved in the bootstrapping process. Also I suggest avoiding the phrase "circular dependencies" in section titles. It gives the impression that it's a feature. The feature is the opposite: the ability to bootstrap (or "cold-start" if that's the term we prefer).

2025-02-24 11:38 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
>  Recovering from a partitioned network is also seamless as only coarse time synchronization between the partitions is required to resume normal operation and move forward with updates of the cryptogra
As for propagation intervals; no I don't think so. Do I need to double check? Should we have a limit to reduce healing time? It is true that paths may take a long time to become known. That's a problem if they break often.

2025-02-24 14:17 UTC, tzaeschke commented on draft-dekater-scion-controlplane.md
> +## Bootstrapping ability
To clarify, my suggestion was to either use only one term (not both) or, otherwise explicitly state that they mean the name thing.
Just using them both without saying that they are the same is probably confusing. I think the least confusing thing would be to have only one term. This may also come up with reviewers.

2025-02-25 09:30 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +## Bootstrapping ability
Indeed, I meant that we choose one and stick to it.

In the current draft version, these are the uses: 
Bootstrap
* ## Bootstrapping ability (this chapter)
* To bootstrap the initial communication with a neighboring beacon service,
* the following bootstrapping strategies apply:
* In the changelog (irrelevant)



Cold start: 
* Interesting metrics for scalability and speed of path discovery are the time until all discoverable path segments have been discovered after a "**cold start**", and the time until new link is usable. 
* On a **cold start** of the network, path segments to each AS are discovered within a numbe
* On a **cold start** of the network, full connectivity is obtained after a number of propagation steps

Plus:
*  In the PKI draft we talk about bootstrapping of trust
* In the DP we talk about one-hop path types  "The OneHopPath path type (PathType=2) is currently used to bootstrap" 

Bootstrap wins, i will change instances of cold start

2025-02-25 09:40 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +## Bootstrapping ability
Done, resolving

2025-02-25 11:12 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
>  - Path segment types: SCION uses different types of path segments to compose end-to-end paths. Notably, a single path segment already enables intra-ISD communication. For example, a non-core AS can r
@jiceatscion do you think this point is relevant to bootstrapping? I don't feel it is that much, so I think it could be removed:
```suggestion
```

2025-02-25 11:13 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +**Note:** For a detailed description of a TRC and more information on the availability of certificates and TRCs, see the SCION Control-Plane PKI {{I-D.dekater-scion-pki}}.
@jiceatscion how are certificates requested? Right now we reference the PKI draft, but I could not find where requesting certs is described. Could we add a better and more precise reference?

2025-02-25 11:23 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +**Note:** For a detailed description of a TRC and more information on the availability of certificates and TRCs, see the SCION Control-Plane PKI {{I-D.dekater-scion-pki}}.
I guess this might be what I am referring to: https://docs.scion.org/en/latest/cryptography/interactions.html

2025-02-25 15:12 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
> +**Note:** For a detailed description of a TRC and more information on the availability of certificates and TRCs, see the SCION Control-Plane PKI {{I-D.dekater-scion-pki}}.
Far as I know, what you want is here: https://github.com/scionproto/scion/blob/abd39afe0a83199aca5ad59d6cc4cc383c89d4cf/proto/control_plane/v1/cppki.proto#L55
I do not know if we described the full pki rpc API anywhere. I wasn't much involved in the cppki draft.

2025-02-25 15:13 UTC, jiceatscion commented on draft-dekater-scion-controlplane.md
> +**Note:** For a detailed description of a TRC and more information on the availability of certificates and TRCs, see the SCION Control-Plane PKI {{I-D.dekater-scion-pki}}.
Indeed, https://docs.scion.org/en/latest/cryptography/interactions.html#messages seems to be as much doc as we have.

2025-02-25 15:53 UTC, nicorusti commented on draft-dekater-scion-controlplane.md
> +**Note:** For a detailed description of a TRC and more information on the availability of certificates and TRCs, see the SCION Control-Plane PKI {{I-D.dekater-scion-pki}}.
https://github.com/scionassociation/scion-cp_I-D/issues/96

2025-02-25 15:55 UTC, nicorusti approved these changes

2025-02-26 09:18 UTC, tzaeschke approved these changes

2025-02-26 09:20 UTC, merged